/** Generated by scripts/optimize-images.mjs — do not edit by hand. */
/** Next-gen srcsets for a local image; absent fields have no sibling. */
export type LocalImageVariant = {
  avifSrcSet?: string;
  webpSrcSet?: string;
};
/** Original local path → generated srcsets (width descriptors included). */
export const LOCAL_IMAGE_VARIANTS: Record<string, LocalImageVariant> = {
  "/assets/images/banners/hero-banner-tumpeng.png": {
    avifSrcSet: "/assets/images/banners/hero-banner-tumpeng-640.avif 640w, /assets/images/banners/hero-banner-tumpeng-1024.avif 1024w, /assets/images/banners/hero-banner-tumpeng-1920.avif 1920w",
    webpSrcSet: "/assets/images/banners/hero-banner-tumpeng-640.webp 640w, /assets/images/banners/hero-banner-tumpeng-1024.webp 1024w, /assets/images/banners/hero-banner-tumpeng-1920.webp 1920w",
  },
  "/assets/images/lifestyle/corporate-lunch-box-overhead-lifestyle.png": {
    avifSrcSet: "/assets/images/lifestyle/corporate-lunch-box-overhead-lifestyle-640.avif 640w",
    webpSrcSet: "/assets/images/lifestyle/corporate-lunch-box-overhead-lifestyle-640.webp 640w",
  },
  "/assets/images/lifestyle/wedding-buffet-lifestyle-shot.png": {
    avifSrcSet: "/assets/images/lifestyle/wedding-buffet-lifestyle-shot-640.avif 640w",
    webpSrcSet: "/assets/images/lifestyle/wedding-buffet-lifestyle-shot-640.webp 640w",
  },
  "/assets/images/patern/songket2.jpg": {
    webpSrcSet: "/assets/images/patern/songket2-opt.webp",
  },
  "/assets/images/products/paket-nasi-box-hemat/paket-nasi-box-hemat-2.png": {
    avifSrcSet: "/assets/images/products/paket-nasi-box-hemat/paket-nasi-box-hemat-2-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-nasi-box-hemat/paket-nasi-box-hemat-2-640.webp 640w",
  },
  "/assets/images/products/paket-nasi-box-hemat/paket-nasi-box-hemat-3.png": {
    avifSrcSet: "/assets/images/products/paket-nasi-box-hemat/paket-nasi-box-hemat-3-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-nasi-box-hemat/paket-nasi-box-hemat-3-640.webp 640w",
  },
  "/assets/images/products/paket-prasmanan-korporat/paket-prasmanan-korporat-1.png": {
    avifSrcSet: "/assets/images/products/paket-prasmanan-korporat/paket-prasmanan-korporat-1-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-prasmanan-korporat/paket-prasmanan-korporat-1-640.webp 640w",
  },
  "/assets/images/products/paket-prasmanan-korporat/paket-prasmanan-korporat-2.png": {
    avifSrcSet: "/assets/images/products/paket-prasmanan-korporat/paket-prasmanan-korporat-2-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-prasmanan-korporat/paket-prasmanan-korporat-2-640.webp 640w",
  },
  "/assets/images/products/paket-prasmanan-nikahan/paket-prasmanan-nikahan-2.png": {
    avifSrcSet: "/assets/images/products/paket-prasmanan-nikahan/paket-prasmanan-nikahan-2-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-prasmanan-nikahan/paket-prasmanan-nikahan-2-640.webp 640w",
  },
  "/assets/images/products/paket-prasmanan-nikahan/paket-prasmanan-nikahan-3.png": {
    avifSrcSet: "/assets/images/products/paket-prasmanan-nikahan/paket-prasmanan-nikahan-3-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-prasmanan-nikahan/paket-prasmanan-nikahan-3-640.webp 640w",
  },
  "/assets/images/products/paket-snack-box-arisan/paket-snack-box-arisan-2.png": {
    avifSrcSet: "/assets/images/products/paket-snack-box-arisan/paket-snack-box-arisan-2-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-snack-box-arisan/paket-snack-box-arisan-2-640.webp 640w",
  },
  "/assets/images/products/paket-tumpeng-mini/paket-tumpeng-mini-2.png": {
    avifSrcSet: "/assets/images/products/paket-tumpeng-mini/paket-tumpeng-mini-2-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-tumpeng-mini/paket-tumpeng-mini-2-640.webp 640w",
  },
  "/assets/images/products/paket-tumpeng-mini/paket-tumpeng-mini-3.png": {
    avifSrcSet: "/assets/images/products/paket-tumpeng-mini/paket-tumpeng-mini-3-640.avif 640w",
    webpSrcSet: "/assets/images/products/paket-tumpeng-mini/paket-tumpeng-mini-3-640.webp 640w",
  },
  "/assets/images/textures/kraft-paper-box-macro-texture.png": {
    avifSrcSet: "/assets/images/textures/kraft-paper-box-macro-texture-640.avif 640w",
    webpSrcSet: "/assets/images/textures/kraft-paper-box-macro-texture-640.webp 640w",
  },
};
